In [1]:
import torch


# Create a Tensor and track its operations

In [4]:
x = torch.ones(2,2, requires_grad=True)
print(x)
y = x +2
print(y)
print(y.grad_fn)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward>)


In [5]:
z = y*y*3
out = z.mean()
print(z,out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward>) tensor(27., grad_fn=<MeanBackward1>)


## The 'requires_grad = False' by deafult as shown below

In [6]:
a=torch.randn(2,2)
a=((a*3)/(a-1))
print(a, a.requires_grad)
a.requires_grad_(True) # the '_' means adding to current variable 'a'
print(a, a.requires_grad)
b =(a*a).sum()
print(b , b.grad_fn)


tensor([[1.2704, 0.0083],
        [1.3691, 1.3884]]) False
tensor([[1.2704, 0.0083],
        [1.3691, 1.3884]], requires_grad=True) True
tensor(5.4159, grad_fn=<SumBackward0>) <SumBackward0 object at 0x0000018BCAEB5EB8>


## Backprop Gradients

In [7]:
out.backward()
print(x.grad) # Print d(out)/dx

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [10]:
x=torch.randn(3, requires_grad = True)
y = x*2
while y.data.norm()< 1000:
    y=y*2
print(y)

tensor([-1960.2168,  -168.8880,   195.3320], grad_fn=<MulBackward>)


In [15]:
v = torch.tensor([0.1,1.0,0.0001], dtype=torch.float)
y.backward(v)
print(x.grad)

tensor([ 307.2000, 3072.0000,    0.3072])


## Stop AutoGrad -  wrap code block 

In [16]:
print(x.requires_grad)
print((x**2).requires_grad)
with torch.no_grad():
    print((x**2).requires_grad)

True
True
False
